depends:
    - uCOS-III
    - platform-abstraction

target.arm:
    - src/main.c
    - src/sensors.c
    - src/mpu60X0.c
    - src/i2c.c
    - src/uart.c
    - src/runtime.c
    - src/system_stm32f4xx.c
    - src/can.c

templates:
    Makefile.jinja: Makefile